services:
  jp:
    build:
      context: .
      dockerfile: 32file
    container_name: fccws
    ports:
      - 8888:8888
    entrypoint:
      jupyter lab --ip='0.0.0.0' --no-browser --allow-root --IdentityProvider.token='' --PasswordIdentityProvider.hashed_password=''
    volumes:
      - jpdata:/app
volumes:
  jpdata:
    name: jpdata